fos_user_security:
    resource: "@HohayaUserBundle/Resources/config/routing/securite.yml"
    prefix: /securite

fos_user_profile:
    resource: "@HohayaUserBundle/Resources/config/routing/profil.yml"
    prefix: /HohayaAdmin/profil

fos_user_register:
    resource: "@HohayaUserBundle/Resources/config/routing/inscription.yml"
    prefix: /HohayaAdmin/inscription

fos_user_resetting:
    resource: "@HohayaUserBundle/Resources/config/routing/reinitialiser.yml"
    prefix: /HohayaAdmin/reinitialisation

fos_user_change_password:
    resource: "@HohayaUserBundle/Resources/config/routing/changer_motdepasse.yml"
    prefix: /HohayaAdmin/changer-motdepasse