services:
    app_user_roles_helper:
        class: HohayaBundle\Services\RolesHelper
        arguments: ['%security.role_hierarchy.roles%']

    app_user.registration.form.type:
        class: Hohaya\UserBundle\Form\Type\RegistrationFormType
        arguments: ['%fos_user.model.user.class%', '@app_user_roles_helper']
        tags:
            - { name: form.type, alias: app_user_registration }

    app_user.profile.form.type:
        class: Hohaya\UserBundle\Form\Type\ProfileFormType
        arguments: ['%fos_user.model.user.class%', '@app_user_roles_helper']
        tags:
            - { name: form.type, alias: app_user_profile }

    app_user.changepassword.form.type:
        class: Hohaya\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: app_user_change_password }
        arguments: ['%fos_user.model.user.class%']