HohayaBundle\Entity\Contrat:
    type: entity
    table: contrat
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contenu:
            type: text
            nullable: false
            length: 0
            options:
                fixed: false
    lifecycleCallbacks: {  }
