HohayaBundle\Entity\Media:
    type: entity
    table: media
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        chemin:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: blob
            nullable: false
            length: 0
            options:
                fixed: false
        extension:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
