HohayaBundle\Entity\Pays:
    type: entity
    table: pays
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomFrFr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nom_fr_fr
        nomGrGr:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nom_gr_gr
    lifecycleCallbacks: {  }
