fos_user_resetting_request:
    path:     /request
    defaults: { _controller: fos_user.resetting.controller:requestAction }
    methods:  [GET]

fos_user_resetting_send_email:
    path:     /send-email
    defaults: { _controller: fos_user.resetting.controller:sendEmailAction }
    methods:  [POST]

fos_user_resetting_check_email:
    path:     /check-email
    defaults: { _controller: fos_user.resetting.controller:checkEmailAction }
    methods:  [GET]

fos_user_resetting_reset:
    path:     /reset/{token}
    defaults: { _controller: fos_user.resetting.controller:resetAction }
    methods:  [GET, POST]
