# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    hohaya.type.publication:
        class: HohayaBundle\Form\PublicationType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }

    hohaya.librairie_controller_service:
        class: HohayaBundle\Controller\LibrairieController
        arguments: [ "@doctrine.orm.entity_manager" ]
        calls:
            - [setContainer, ["@service_container"]]

    hohaya_user.profile.controller:
        class: Hohaya\UserBundle\Controller\UtilisateurController
        arguments: ['@event_dispatcher', '@fos_user.profile.form.factory', '@fos_user.user_manager']
        calls:
            - [setContainer, ['@service_container']]

    hohaya_user.registration.controller:
        class: Hohaya\UserBundle\Controller\RegistrationController
        arguments: ['@event_dispatcher', '@fos_user.registration.form.factory', '@fos_user.user_manager', '@security.token_storage']
        calls:
            - [setContainer, ['@service_container']]

    hohaya_user.security.controller:
        class: Hohaya\UserBundle\Controller\SecurityController
        arguments: ['@?security.csrf.token_manager']
        calls:
            - [setContainer, ['@service_container']]

    hohaya_user.change_password.controller:
        class: Hohaya\UserBundle\Controller\ChangePasswordController
        arguments: ['@event_dispatcher', '@fos_user.change_password.form.factory', '@fos_user.user_manager']
        calls:
            - [setContainer, ['@service_container']]
