<?php

namespace HohayaBundle\Repository;

/**
 * LocationCaracteristiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationCaracteristiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
