<?php

namespace HohayaBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM HohayaBundle:Menu m WHERE m.supprimer = 0 ORDER BY m.ordreAffichage ASC'
            )
            ->getResult();
    }
}
