<?php

namespace HohayaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function listeSlides()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p, s FROM HohayaBundle:Publication p
		        JOIN p.smenu s
		        WHERE s.id = :id
                AND p.supprimer = 0
                AND p.estSlide = 1
		        ORDER BY p.id DESC"
            )->setParameter('id', 6)
            ->setMaxResults (3)
            ->setFirstResult(0)
            ->getResult();
    }

    public function listeDerniereNouvelles()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p, s FROM HohayaBundle:Publication p
		        JOIN p.smenu s
		        WHERE s.id = :id
                AND p.supprimer = 0
		        ORDER BY p.id DESC"
            )->setParameter('id', 6)
            ->setMaxResults (8)
            ->setFirstResult(0)
            ->getResult();
    }

    public function paginate($cle, $id, $rowsperpage, $offset)
    {
        switch ($cle) {
            case 'm':
                return $this->getEntityManager()
                ->createQuery(
                    "SELECT p, m FROM HohayaBundle:Publication p
                    JOIN p.menu m
                    WHERE m.id = :id
                    AND p.supprimer = 0
                    ORDER BY p.id DESC"
                )
                ->setParameter('id', $id)
                ->setMaxResults ($rowsperpage)
                ->setFirstResult($offset)
                ->getResult();
                break;

            case 'sm':
                return $this->getEntityManager()
                ->createQuery(
                    "SELECT p, sm FROM HohayaBundle:Publication p
                    JOIN p.smenu sm
                    WHERE sm.id = :id
                    AND p.supprimer = 0
                    ORDER BY p.id DESC"
                )
                ->setParameter('id', $id)
                ->setMaxResults ($rowsperpage)
                ->setFirstResult($offset)
                ->getResult();
                break;

            case 'ssm':
                return $this->getEntityManager()
                ->createQuery(
                    "SELECT p, ssm FROM HohayaBundle:Publication p
                    JOIN p.ssmenu ssm
                    WHERE ssm.id = :id
                    AND p.supprimer = 0
                    ORDER BY p.id DESC"
                )
                ->setParameter('id', $id)
                ->setMaxResults ($rowsperpage)
                ->setFirstResult($offset)
                ->getResult();
                break;

            case 'photo':
                return $this->getEntityManager()
                ->createQuery(
                    "SELECT p FROM HohayaBundle:Publication p
                    WHERE (p.nomImage LIKE '%.jpeg') or (p.nomImage LIKE '%.png') or (p.nomImage LIKE '%.jpg')
                    AND p.supprimer = 0
                    ORDER BY p.id DESC"
                )
                ->setMaxResults ($rowsperpage)
                ->setFirstResult($offset)
                ->getResult();
                break;
            
            default:
                # code...
                break;
        }
    }

    public function listeLienUtile()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p, m FROM HohayaBundle:Publication p
                JOIN p.menu m
                WHERE m.id = :id
                AND p.supprimer = 0
                ORDER BY p.id DESC"
            )->setParameter('id', 10)
            ->setMaxResults (5)
            ->setFirstResult(0)
            ->getResult();
    }

    public function listeBonASavoir()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p, m FROM HohayaBundle:Publication p
                JOIN p.menu m
                WHERE m.id = :id
                AND p.supprimer = 0
                ORDER BY p.id DESC"
            )->setParameter('id', 9)
            ->setMaxResults (3)
            ->setFirstResult(0)
            ->getResult();
    }


      public function listeCommunique()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p, s FROM HohayaBundle:Publication p
		        JOIN p.smenu s
		        WHERE s.id = :id
                AND p.supprimer = 0
		        ORDER BY p.id DESC"
            )->setParameter('id', 8)
            ->setMaxResults (3)
            ->setFirstResult(0)
            ->getResult();
    }

    public function listeAppelDOffre()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM HohayaBundle:Publication p
		        WHERE p.titre = :titre
                AND p.supprimer = 0
		        ORDER BY p.id DESC"
            )->setParameter('titre', 'Appel d\'Offre')
            ->getResult();
    }

    public function findSevenLastNews()
    {
    	$rsm = new ResultSetMapping();
		// build rsm here

		$query = $this->getEntityManager()
			->createNativeQuery('
			SELECT *
			FROM publication WHERE supprimer = 0', $rsm);
		//$query->setParameter(1, 6);

		$sevenLastNews = $query->getResult();

		return $sevenLastNews;
    }

    public function listePhoto()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM HohayaBundle:Publication p
                WHERE (p.nomImage LIKE '%.jpeg') or (p.nomImage LIKE '%.png') or (p.nomImage LIKE '%.jpg')
                AND p.supprimer = 0
                ORDER BY p.id DESC"
            )->getResult();
    }
}
