<?php

namespace HohayaBundle\Repository;

/**
 * SousTypeLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTypeLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
