<?php

namespace HohayaBundle\Repository;

/**
 * TypePersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
