<?php

namespace HohayaBundle\Repository;

/**
 * TypeLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
